# permissions for end users to view podcleanups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: awesomeproject
    app.kubernetes.io/managed-by: kustomize
  name: podcleanup-viewer-role
rules:
- apiGroups:
  - batch.example.com
  resources:
  - podcleanups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.example.com
  resources:
  - podcleanups/status
  verbs:
  - get
