---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - batch.example.com
  resources:
  - podcleanups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.example.com
  resources:
  - podcleanups/finalizers
  verbs:
  - update
- apiGroups:
  - batch.example.com
  resources:
  - podcleanups/status
  verbs:
  - get
  - patch
  - update
